#define GREEN   "\033[1;32m"
#define RESET   "\033[0m"

#define WELCOME_MSG GREEN "WELCOME TO THE AMAZING TECHNOLOGY OF PHONEBOOK\n" RESET
#define WELCOME_MSG_L 59

#define CHS_MSG GREEN "YOU CAN CHOOSE BETWEEN THESE 3 ACTIONS:\n" \
                            "ADD, SEARCH, EXIT\n" RESET
#define CHS_MSG_L 70

#define FN_MSG GREEN "PLEASE, ENTER THE FIRST NAME OF THE CONTACT:\n" RESET
#define FN_MSG_L 57

#define ADDED_MSG GREEN "THE CONTACT HAS BEEN ADDED SUCCESFULLY\n" RESET
#define ADDED_MSG_L 51