#define GREEN "\033[1;32m"
#define BLUE "\033[1;36m"
#define RESET "\033[0m"

#define WELCOME_MSG GREEN "WELCOME TO THE AMAZING TECHNOLOGY OF PHONEBOOK\n" RESET
#define WELCOME_MSG_L 59

#define CHS_MSG GREEN "YOU CAN CHOOSE BETWEEN THESE 3 ACTIONS:\n" \
                            "ADD, SEARCH, EXIT\n" RESET
#define CHS_MSG_L 70

#define FN_MSG GREEN "PLEASE, ENTER THE FIRST NAME OF THE CONTACT:\n" RESET
#define FN_MSG_L 57

#define LN_MSG GREEN "JUST IN CASE... A LAST NAME?\n" RESET
#define LN_MSG_L 41

#define NN_MSG GREEN "WHAT ABOUT A FUNNY NAME OR SOME KIND OF SECRET NAME?\n" RESET
#define NN_MSG_L 65

#define PN_MSG GREEN "NOW THE IMPORTANT PART: WE NEED A NUMBER TO CALL THEM\n" RESET
#define PN_MSG_L 66

#define DS_MSG GREEN "BETWEEN YOU AND ME...\n" \
                        "WICH IS THE DARKEST THING YOU KNOW ABOUT THEM?\n" RESET
#define DS_MSG_L 81

#define ADDED_MSG GREEN "THE CONTACT HAS BEEN ADDED SUCCESFULLY\n" RESET
#define ADDED_MSG_L 51